NAME: 'orgmim'


MODEL:
  scale: 'small' # small, base, large
  arch: 'vit' # vit or cnn
  pre_train: False
  continue_train: False
  pretrain_path: 
  continue_path: 
  img_size: 128
  patch_size: 16
  num_classes: 2


TRAIN:
  cache_path: './caches/'
  save_path: './models/'
  group_path: 
  display_freq: 100
  total_iters: 400000
  warmup_iters: 0
  base_lr: 0.0001
  end_lr: 0.0001
  save_freq: 2000
  valid_freq: 1000
  decay_iters: 200000
  weight_decay: ~
  power: 1.5
  batch_size: 4
  num_workers: 16
  if_cuda: True
  random_seed: 666
  loss_forward: 3
  alpha_t: 0.75
  mask_ratio: 0.75


DATA:
  data_folder: '/***/***'
  mam_folder: '/***/***'
 

