NAME: 'orgmim'

MODEL:
  pre_train: False
  continue_train: True
  pretrain_path: 
  continue_path: '/opt/data/3_33/SCN/zhangyc/SegOrganelle/Code/Dual_Stream_MAE/models/Dual_MAE'
  dim: 768
  depth: 12
  head: 12
  mlp_dim: 3072
  img_size: 128
  patch_size: 16


TRAIN:
  cache_path: './caches/'
  save_path: './models/'
  group_path: '/opt/data/3_33/SCN/zhangyc/SegOrganelle/Code/pretrain_github/ViT/group_file.json'
  loss_forward: 3
  mask_ratio: 0.75
  alpha_t: 0.75
  display_freq: 100
  total_iters: 400000
  warmup_iters: 0
  base_lr: 0.0001
  end_lr: 0.0001
  save_freq: 2000
  valid_freq: 1000
  decay_iters: 200000
  weight_decay: ~
  power: 1.5
  batch_size: 2
  num_workers: 16
  if_cuda: True
  random_seed: 666  


DATA:
  data_folder: '***/***'
  mam_folder: '***/***'
 


